# Generated by Django 5.0.4 on 2024-04-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_person_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
