# Generated by Django 5.0.4 on 2024-04-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_person_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
